version: '3'

services:
  api:
    build: .
    container_name: api
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    environment:
        NODE_ENV: "development"
    depends_on:
      - postgres-db
    networks:
      - api-network
  postgres-db:
    image: postgres
    ports:
        - '5432:5432'
    environment:
        POSTGRES_PASSWORD: docker
    networks:
        - api-network

networks:
  api-network:
    driver: bridge