version: '3'

services:
  api:
    build: .
    container_name: api
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    environment:
        NODE_ENV: "development"
    depends_on:
      - postgres-db
    networks:
      - api-network
  postgres-db:
    image: postgres
    ports:
        - '5432:5432'
    environment:
        POSTGRES_PASSWORD: docker
    networks:
        - api-network
  migration:
    environment:
        NODE_ENV: "development"
    build: .

    command: ["./wait-for-it.sh", "127.0.0.1:5432", "--", "yarn","create-database", "--", "yarn", "migrate"]
    container_name: api-nodejs-migrate
    links:
        - postgres-db
    depends_on:
        - api
        - postgres-db
    networks:
        - api-network
networks:
  api-network:
    driver: bridge

##TODO fix migration